import "./Home.css";
import "./NavBar";

import Carousel from "react-bootstrap/Carousel";
import { Link } from "react-router-dom";

function Home({ user }) {
  if (user) {
    return <h1>Welcome, {user.username}!</h1>;
  } else {
    return (
      <>
        <div className="hero">
          <div className="ContentPlaceToVisit">
            <div className="ContentImage">
              <Carousel>
                <Carousel.Item interval={1000}>
                  <img
                    className="d-block w-100 img"
                    src="https://images.pexels.com/photos/13348192/pexels-photo-13348192.jpeg?cs=srgb&dl=pexels-antony-trivet-13348192.jpg&fm=jpg"
                    alt="First slide"
                  />
                  <Carousel.Caption className="d-flex justify-content-center align-items-center flex-column h-100">
                    <h3 className="text-center">Explore Nairobi</h3>
                    <div className="flex justify-center items-center mt-4">
                      <Link to="/spaces">
                        <button className="rounded-full bg-orange-500 hover:bg-blue-700 text-white font-bold py-2 px-4">
                          View Spaces
                        </button>
                      </Link>
                    </div>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item interval={500}>
                  <img
                    className="d-block w-100 img"
                    src="https://images.squarespace-cdn.com/content/v1/52f00078e4b089eccb42cf0e/1425317913558-9MR0N1W0D49EBZXJZ521/Mombasa+by+Night"
                    alt="Second slide"
                  />
                  <Carousel.Caption className="d-flex justify-content-center align-items-center flex-column h-100">
                    <h3 className="text-center">Explore Mombasa</h3>
                    <div className="flex justify-center items-center mt-4">
                      <Link to="/spaces">
                        <button className="rounded-full bg-orange-500 hover:bg-blue-700 text-white font-bold py-2 px-4">
                          View Spaces
                        </button>
                      </Link>
                    </div>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                  <img
                    className="d-block w-100 img"
                    src="https://www.danstalter.com/wp-content/uploads/2018/12/IMG_20180922_175913.jpg"
                    alt="Third slide"
                  />
                  <Carousel.Caption className="d-flex justify-content-center align-items-center flex-column h-100">
                    <h3 className="text-center text 4xl">Explore Kisumu</h3>
                    <div className="flex justify-center items-center mt-4">
                      <Link to="/spaces">
                        <button className="rounded-full bg-orange-500 hover:bg-blue-700 text-white font-bold py-2 px-4">
                          View Spaces
                        </button>
                      </Link>
                    </div>
                  </Carousel.Caption>
                </Carousel.Item>
              </Carousel>
            </div>
          </div>
          {/* ABout Us  */}
          <div>
            <div className="2xl:mx-auto 2xl:container 2xl:px-20 px-6 ">
              <div className="flex md:flex-row flex-col-reverse md:items-stretch items-center justify-center">
                <div className="md:py-20 xl:w-1/2 sm:w-1/2 lg:mr-20 md:mr-6 flex flex-col md:items-end items-center justify-center xl:mr-28">
                  <div className="flex flex-col items-center justify-center">
                    <h1 className="md:text-5xl text-3xl font-bold text-center text-gray-800">
                      LEISURE SPACE
                    </h1>
                    <p className="sm:w-96 w-full mt-6 text-base leading-6 text-center text-gray-600">
                      Leisure Space is an online marketplace that connects users
                      with unique and cool spaces that can be rented by the hour
                      or day for meetings, events, or activities. The platform
                      brings together people with a shared passion or interest
                      in a particular area, allowing them to meet, create, and
                      celebrate within a cool environment generated by willing
                      space owners around the country.
                    </p>

                    <div className="mt-7 flex flex-col items-center">
                      <div
                        className="w-20 h-20 bg-white shadow rounded-full flex items-center justify-center"
                        role="img"
                        aria-label="phone"
                      >
                        <svg
                          width="26"
                          height="26"
                          viewBox="0 0 26 26"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M3.66667 2.33331H9L11.6667 8.99998L8.33333 11C9.76128 13.8954 12.1046 16.2387 15 17.6666L17 14.3333L23.6667 17V22.3333C23.6667 23.0406 23.3857 23.7188 22.8856 24.2189C22.3855 24.719 21.7072 25 21 25C15.799 24.6839 10.8935 22.4753 7.20911 18.7909C3.52467 15.1064 1.31607 10.201 1 4.99998C1 4.29274 1.28095 3.61446 1.78105 3.11436C2.28115 2.61426 2.95942 2.33331 3.66667 2.33331Z"
                            stroke="#4338CA"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M17 6.33331C17.7072 6.33331 18.3855 6.61426 18.8856 7.11436C19.3857 7.61446 19.6667 8.29274 19.6667 8.99998"
                            stroke="#4338CA"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                          <path
                            d="M17 1C19.1217 1 21.1566 1.84286 22.6569 3.34315C24.1571 4.84344 25 6.87827 25 9"
                            stroke="#4338CA"
                            stroke-width="1.5"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                          />
                        </svg>
                      </div>
                      <p className="text-base leading-6 mt-6 text-center text-gray-600 sm:w-96 w-full">
                        Phone number 07941178
                      </p>
                      <p>Email leisurespace@gmail.com</p>
                    </div>
                  </div>
                </div>
                <div className="py-12 xl:w-1/2 lg:w-1/3 sm:w-1/2">
                  <img
                    src="https://i.pinimg.com/564x/1d/3f/ae/1d3faef4032474a2bff76cd662c7e735.jpg"
                    alt="image ow a woman studying"
                    className="h-full rounded-md object-cover object-center md:block hidden"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    );
  }
}
export default Home;
